# Generated by Django 5.2.5 on 2025-11-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretor',
            options={'verbose_name': 'Corretor', 'verbose_name_plural': 'Corretores'},
        ),
        migrations.AlterModelOptions(
            name='modelo3d',
            options={'verbose_name': 'Modelo 3D', 'verbose_name_plural': 'Modelos 3D'},
        ),
    ]
