# Generated by Django 5.1.7 on 2025-06-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='proprietarios', to='core.proprietario'),
            preserve_default=False,
        ),
    ]
