# Generated by Django 5.2.7 on 2025-11-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_corretor_options_alter_modelo3d_options'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='modelo_glb',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document'),
        ),
    ]
