# Generated by Django 5.1.7 on 2025-06-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propriedade_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100)),
                ('creci', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuarios', to='core.usuario')),
            ],
        ),
    ]
