# Generated by Django 5.1.7 on 2025-06-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_rename_descricao_propriedade_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='datanasc',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
    ]
