# Generated by Django 5.2.7 on 2025-10-31 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_cpf_alter_usuario_datanasc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proprietarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
