# Generated by Django 5.2.7 on 2025-11-06 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_corretor_nome_alter_proprietario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Passage ID', unique=True, verbose_name='passage_id'),
        ),
    ]
