# Generated by Django 5.2.7 on 2025-11-11 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_passage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='propriedade',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
