# Generated by Django 5.2.7 on 2025-11-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_propriedade_proprietario_propriedade_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proprietario',
        ),
    ]
