# Generated by Django 5.2.7 on 2025-11-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='modelo_3d',
        ),
    ]
